IF OBJECT_ID('USERS', 'U') IS NULL
BEGIN
  CREATE TABLE USERS (
    user_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    name NVARCHAR(200) NOT NULL,
    email NVARCHAR(320) NOT NULL,
    mobile NVARCHAR(20) NOT NULL,
    role NVARCHAR(40) NOT NULL,
    tenant_id NVARCHAR(100) NOT NULL,
    company_id NVARCHAR(100) NOT NULL,
    branch_id NVARCHAR(100) NOT NULL,
    firm_name NVARCHAR(200) NOT NULL,
    password_hash NVARCHAR(500) NOT NULL,
    is_active BIT NOT NULL DEFAULT 1,
    must_change_password BIT NOT NULL DEFAULT 1,
    last_login_at DATETIME2 NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_USERS_EMAIL')
BEGIN
  CREATE UNIQUE INDEX UX_USERS_EMAIL ON USERS (email);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_USERS_MOBILE')
BEGIN
  CREATE UNIQUE INDEX UX_USERS_MOBILE ON USERS (mobile);
END
GO

IF COL_LENGTH('USERS', 'email_verified_at') IS NULL
BEGIN
  ALTER TABLE USERS ADD email_verified_at DATETIME2 NULL;
END
GO

IF OBJECT_ID('REFRESH_TOKENS', 'U') IS NULL
BEGIN
  CREATE TABLE REFRESH_TOKENS (
    token_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    token_hash CHAR(64) NOT NULL,
    user_id NVARCHAR(100) NOT NULL,
    expires_at DATETIME2 NOT NULL,
    created_at DATETIME2 NOT NULL,
    CONSTRAINT FK_REFRESH_TOKENS_USERS FOREIGN KEY (user_id)
      REFERENCES USERS(user_id) ON DELETE CASCADE
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_REFRESH_TOKENS_HASH')
BEGIN
  CREATE UNIQUE INDEX UX_REFRESH_TOKENS_HASH ON REFRESH_TOKENS (token_hash);
END
GO

IF OBJECT_ID('AUTH_OTP_CODES', 'U') IS NULL
BEGIN
  CREATE TABLE AUTH_OTP_CODES (
    otp_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    user_id NVARCHAR(100) NOT NULL,
    purpose NVARCHAR(40) NOT NULL,
    code_hash CHAR(64) NOT NULL,
    expires_at DATETIME2 NOT NULL,
    attempts_remaining INT NOT NULL DEFAULT 5,
    created_at DATETIME2 NOT NULL,
    CONSTRAINT FK_AUTH_OTP_CODES_USERS FOREIGN KEY (user_id)
      REFERENCES USERS(user_id) ON DELETE CASCADE
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AUTH_OTP_CODES_USER_PURPOSE')
BEGIN
  CREATE INDEX IX_AUTH_OTP_CODES_USER_PURPOSE
  ON AUTH_OTP_CODES (user_id, purpose, expires_at DESC);
END
GO

IF OBJECT_ID('COMMANDS', 'U') IS NULL
BEGIN
  CREATE TABLE COMMANDS (
    command_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    idempotency_key NVARCHAR(180) NULL,
    tenant_id NVARCHAR(100) NOT NULL,
    company_id NVARCHAR(100) NOT NULL,
    branch_id NVARCHAR(100) NOT NULL,
    financial_year NVARCHAR(25) NOT NULL,
    user_id NVARCHAR(100) NOT NULL,
    conversation_id NVARCHAR(100) NOT NULL,
    input_type NVARCHAR(20) NOT NULL,
    transcript NVARCHAR(MAX) NOT NULL,
    intent NVARCHAR(100) NOT NULL,
    status NVARCHAR(40) NOT NULL,
    requires_confirmation BIT NOT NULL DEFAULT 0,
    risk_level NVARCHAR(20) NOT NULL,
    result_json NVARCHAR(MAX) NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL,
    completed_at DATETIME2 NULL
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_COMMANDS_TENANT_IDEMPOTENCY')
BEGIN
  CREATE INDEX IX_COMMANDS_TENANT_IDEMPOTENCY
  ON COMMANDS (tenant_id, idempotency_key, created_at DESC);
END
GO

IF OBJECT_ID('CONVERSATIONS', 'U') IS NULL
BEGIN
  CREATE TABLE CONVERSATIONS (
    conversation_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    tenant_id NVARCHAR(100) NOT NULL,
    company_id NVARCHAR(100) NOT NULL,
    branch_id NVARCHAR(100) NOT NULL,
    financial_year NVARCHAR(25) NOT NULL,
    user_id NVARCHAR(100) NOT NULL,
    status NVARCHAR(40) NOT NULL,
    current_intent NVARCHAR(100) NOT NULL,
    pending_field NVARCHAR(100) NULL,
    pending_question NVARCHAR(300) NULL,
    context_json NVARCHAR(MAX) NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CONVERSATIONS_TENANT_USER')
BEGIN
  CREATE INDEX IX_CONVERSATIONS_TENANT_USER
  ON CONVERSATIONS (tenant_id, user_id, updated_at DESC);
END
GO

IF OBJECT_ID('CONVERSATION_MESSAGES', 'U') IS NULL
BEGIN
  CREATE TABLE CONVERSATION_MESSAGES (
    message_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    conversation_id NVARCHAR(100) NOT NULL,
    sender NVARCHAR(20) NOT NULL,
    message_type NVARCHAR(40) NOT NULL,
    [text] NVARCHAR(MAX) NOT NULL,
    metadata_json NVARCHAR(MAX) NULL,
    created_at DATETIME2 NOT NULL
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CONV_MSG_CONVERSATION')
BEGIN
  CREATE INDEX IX_CONV_MSG_CONVERSATION
  ON CONVERSATION_MESSAGES (conversation_id, created_at);
END
GO

IF OBJECT_ID('AUDIT_LOG', 'U') IS NULL
BEGIN
  CREATE TABLE AUDIT_LOG (
    audit_id NVARCHAR(100) NOT NULL PRIMARY KEY,
    tenant_id NVARCHAR(100) NOT NULL,
    company_id NVARCHAR(100) NOT NULL,
    user_id NVARCHAR(100) NOT NULL,
    command_id NVARCHAR(100) NOT NULL,
    action NVARCHAR(120) NOT NULL,
    entity_type NVARCHAR(100) NOT NULL,
    entity_id NVARCHAR(100) NOT NULL,
    before_json NVARCHAR(MAX) NULL,
    after_json NVARCHAR(MAX) NULL,
    result NVARCHAR(40) NOT NULL,
    created_at DATETIME2 NOT NULL
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AUDIT_TENANT_CREATED')
BEGIN
  CREATE INDEX IX_AUDIT_TENANT_CREATED
  ON AUDIT_LOG (tenant_id, created_at DESC);
END
GO

IF OBJECT_ID('CLIENT_GST_PORTAL_CONNECTIONS', 'U') IS NULL
BEGIN
  CREATE TABLE CLIENT_GST_PORTAL_CONNECTIONS (
    tenant_id NVARCHAR(100) NOT NULL,
    company_id NVARCHAR(100) NOT NULL,
    connection_type NVARCHAR(30) NOT NULL,
    is_enabled BIT NOT NULL DEFAULT 0,
    applicability_threshold DECIMAL(18,2) NULL,
    provider_name NVARCHAR(100) NOT NULL,
    base_url NVARCHAR(500) NOT NULL,
    auth_type NVARCHAR(30) NOT NULL,
    credential_ciphertext NVARCHAR(MAX) NOT NULL,
    credential_iv NVARCHAR(100) NOT NULL,
    credential_tag NVARCHAR(100) NOT NULL,
    created_by NVARCHAR(100) NOT NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL,
    CONSTRAINT PK_CLIENT_GST_PORTAL_CONNECTIONS PRIMARY KEY
      (tenant_id, company_id, connection_type)
  );
END
GO

IF COL_LENGTH('CLIENT_GST_PORTAL_CONNECTIONS', 'is_enabled') IS NULL
BEGIN
  ALTER TABLE CLIENT_GST_PORTAL_CONNECTIONS
  ADD is_enabled BIT NOT NULL DEFAULT 0;
END
GO

IF COL_LENGTH('CLIENT_GST_PORTAL_CONNECTIONS', 'applicability_threshold') IS NULL
BEGIN
  ALTER TABLE CLIENT_GST_PORTAL_CONNECTIONS
  ADD applicability_threshold DECIMAL(18,2) NULL;
END
GO
