CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(320) NOT NULL,
  mobile VARCHAR(20) NULL,
  firm_name VARCHAR(200) NOT NULL DEFAULT 'Chirag Accounting',
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'user',
  account_origin VARCHAR(40) NOT NULL DEFAULT 'legacyUnknown',
  client_status VARCHAR(40) NOT NULL DEFAULT 'active',
  login_status VARCHAR(40) NOT NULL DEFAULT 'active',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  identity_revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY users_email_unique (email),
  UNIQUE KEY users_mobile_unique (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_profiles (
  client_id INT NOT NULL,
  legal_name VARCHAR(200) NOT NULL DEFAULT '',
  gstin VARCHAR(15) NOT NULL DEFAULT '',
  pan VARCHAR(20) NOT NULL DEFAULT '',
  aadhaar VARCHAR(20) NOT NULL DEFAULT '',
  address_line VARCHAR(500) NOT NULL DEFAULT '',
  city VARCHAR(120) NOT NULL DEFAULT '',
  state VARCHAR(120) NOT NULL DEFAULT '',
  pincode VARCHAR(12) NOT NULL DEFAULT '',
  country VARCHAR(80) NOT NULL DEFAULT 'India',
  registered_location_json JSON NULL,
  logo_file_name VARCHAR(255) NOT NULL DEFAULT '',
  logo_data_base64 MEDIUMTEXT NULL,
  invoice_format VARCHAR(100) NOT NULL DEFAULT 'Classic',
  document_metadata_json JSON NULL,
  created_by INT NULL,
  updated_by INT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  KEY client_profiles_gstin_idx (gstin),
  CONSTRAINT fk_client_profiles_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_profiles_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_client_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_compliance (
  client_id INT NOT NULL,
  gst_registration_type VARCHAR(40) NOT NULL DEFAULT 'unregistered',
  accounting_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  gst_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  services_json JSON NOT NULL,
  service_periods_json JSON NOT NULL,
  created_by INT NULL,
  updated_by INT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  CONSTRAINT fk_client_compliance_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_compliance_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_client_compliance_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_assignments (
  client_id INT NOT NULL,
  accountant_user_id INT NULL,
  ca_user_id INT NULL,
  assigned_by INT NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'active',
  old_accounting_approved BOOLEAN NOT NULL DEFAULT FALSE,
  reports_published BOOLEAN NOT NULL DEFAULT FALSE,
  audit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  financial_statements_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  report_signing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  bank_project_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  staff_delegation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  KEY client_assignments_accountant_idx (accountant_user_id, status),
  KEY client_assignments_ca_idx (ca_user_id, status),
  CONSTRAINT fk_client_assignments_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_assignments_accountant FOREIGN KEY (accountant_user_id) REFERENCES users (id),
  CONSTRAINT fk_client_assignments_ca FOREIGN KEY (ca_user_id) REFERENCES users (id),
  CONSTRAINT fk_client_assignments_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_access_policies (
  client_id INT NOT NULL,
  login_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  mobile_login_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  web_login_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  two_factor_required BOOLEAN NOT NULL DEFAULT FALSE,
  account_locked BOOLEAN NOT NULL DEFAULT FALSE,
  subscription_plan VARCHAR(40) NOT NULL DEFAULT 'standard',
  billing_mode VARCHAR(60) NOT NULL DEFAULT 'fullBillingSoftware',
  accounting_mode VARCHAR(60) NOT NULL DEFAULT 'accountsOnly',
  purchase_entry_mode VARCHAR(30) NOT NULL DEFAULT 'both',
  sales_entry_mode VARCHAR(30) NOT NULL DEFAULT 'both',
  modules_json JSON NOT NULL,
  dashboard_widgets_json JSON NOT NULL,
  document_hub_access_json JSON NOT NULL,
  created_by INT NULL,
  updated_by INT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  CONSTRAINT fk_client_access_policies_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_access_policies_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_client_access_policies_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_workspaces (
  client_id INT NOT NULL,
  client_360_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  document_folder_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  compliance_workspace_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  accounting_workspace_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ai_workspace_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  notification_settings_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by INT NULL,
  updated_by INT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  CONSTRAINT fk_client_workspaces_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_workspaces_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_client_workspaces_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_data_change_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id INT NOT NULL,
  actor_user_id INT NOT NULL,
  change_type VARCHAR(80) NOT NULL,
  payload_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY client_data_change_log_client_idx (client_id, created_at),
  KEY client_data_change_log_actor_idx (actor_user_id, created_at),
  CONSTRAINT fk_client_data_change_log_client FOREIGN KEY (client_id) REFERENCES users (id),
  CONSTRAINT fk_client_data_change_log_actor FOREIGN KEY (actor_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_migration_reconciliation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_system VARCHAR(80) NOT NULL,
  source_record_id VARCHAR(255) NOT NULL,
  target_table VARCHAR(80) NOT NULL,
  target_record_id VARCHAR(255) NULL,
  payload_hash CHAR(64) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
  source_payload_json JSON NOT NULL,
  conflict_reason VARCHAR(500) NOT NULL DEFAULT '',
  reviewed_by INT NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY data_migration_reconciliation_source_unique (source_system, source_record_id, target_table, payload_hash),
  KEY data_migration_reconciliation_status_idx (status, created_at),
  CONSTRAINT fk_data_migration_reconciliation_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;