import { useState } from 'react';
import type { VoucherType } from '../types';
import { financialYear, getSeries, saveSeries, type VoucherNumberSeries } from '../store/voucherNumbering';
import { VOUCHER_SHORTCUTS } from '../data/voucherShortcuts';

export default function VoucherNumberingPanel() {
  const fy = financialYear();
  const [selectedType, setSelectedType] = useState<VoucherType>('Sales');
  const [series, setSeries] = useState<VoucherNumberSeries>(() => getSeries('Sales', fy));
  const [message, setMessage] = useState('');
  function select(type: VoucherType) { setSelectedType(type); setSeries(getSeries(type, fy)); setMessage(''); }
  function submit() { const result = saveSeries(selectedType, series, fy); setMessage(result.error ?? `${selectedType} series saved for FY ${fy}.`); if (result.ok) setSeries(getSeries(selectedType, fy)); }
  return <div className="space-y-4"><div><h3 className="text-xs font-bold uppercase tracking-wide text-slate-600">Voucher Numbering</h3><p className="mt-1 text-xs text-slate-500">Financial Year {fy}. Once the first voucher is saved, this series cannot be changed.</p></div><div><label className="block text-[11px] font-semibold uppercase text-slate-500">Voucher Type</label><select className="mt-1 w-full rounded-md border border-slate-300 px-2.5 py-1.5 text-sm" value={selectedType} onChange={(e) => select(e.target.value as VoucherType)}>{VOUCHER_SHORTCUTS.map((item) => <option key={item.type} value={item.type}>{item.type}</option>)}</select></div><div><label className="block text-[11px] font-semibold uppercase text-slate-500">Prefix</label><input disabled={series.locked} className="mt-1 w-full rounded-md border border-slate-300 px-2.5 py-1.5 text-sm disabled:bg-slate-100" value={series.prefix} onChange={(e) => setSeries({ ...series, prefix: e.target.value })} /></div><div className="grid grid-cols-2 gap-3"><label className="text-sm text-slate-700"><input disabled={series.locked} type="radio" checked={series.mode === 'auto'} onChange={() => setSeries({ ...series, mode: 'auto' })} /> Auto</label><label className="text-sm text-slate-700"><input disabled={series.locked} type="radio" checked={series.mode === 'manual'} onChange={() => setSeries({ ...series, mode: 'manual' })} /> Manual</label></div><div><label className="block text-[11px] font-semibold uppercase text-slate-500">Starting / Next Number</label><input disabled={series.locked} type="number" min="1" className="mt-1 w-full rounded-md border border-slate-300 px-2.5 py-1.5 text-sm disabled:bg-slate-100" value={series.nextNumber} onChange={(e) => setSeries({ ...series, nextNumber: Number(e.target.value) || 0 })} /></div>{series.locked && <p className="rounded bg-amber-50 px-3 py-2 text-xs text-amber-800">Locked: voucher series has been used in this financial year.</p>}{message && <p className="text-xs text-slate-600">{message}</p>}<button disabled={series.locked} onClick={submit} className="w-full rounded-md bg-blue-600 py-2 text-sm font-semibold text-white disabled:bg-slate-300">Save Numbering Setup</button></div>;
}